services:
  backend:
    build:
      context: fastapi_backend
    environment:
      - OPENAPI_OUTPUT_FILE=./shared-data/openapi.json
      - DATABASE_URL=${DATABASE_URL}
      - TEST_DATABASE_URL=mysql+aiomysql://root:dtcc-hack@singlestore:3306/test # use this for local tests, after manual "CREATE DATABASE test"
      - MAIL_SERVER=mailhog
    ports:
      - "8000:8000"
    networks:
      - my_network
    volumes:
      - ./fastapi_backend:/app
      - fastapi-venv:/app/.venv
      - ./local-shared-data:/app/shared-data
    depends_on:
      - singlestore # for local tests
  singlestore:
    # test connectivity from backend with...
    #   mysql -h singlestore -P 3306 -u root --password="dtcc-hack" --prompt="singlestore> " --database=""
    image: singlestore/cluster-in-a-box
    platform: linux/amd64
    environment:
      - LICENCE_KEY=REDACTED # https://portal.singlestore.com/organizations/02f09220-558c-4cbd-bd7a-040b7b490afe/licenses/install-guide/
      - ROOT_PASSWORD=dtcc-hack
    ports:
      - "8080:8080"
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - singlestore_data:/var/lib/memsql
  frontend:
    build:
      context: ./nextjs-frontend
    user: node
    ports:
      - "3000:3000"
    networks:
      - my_network
    environment:
      NODE_ENV: development
      API_BASE_URL: http://backend:8000
      OPENAPI_OUTPUT_FILE: ./shared-data/openapi.json
    volumes:
      - ./nextjs-frontend:/app
      - nextjs-node-modules:/app/node_modules
      - ./local-shared-data:/app/shared-data
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    networks:
      - my_network

volumes:
  postgres_data:
  nextjs-node-modules:
  fastapi-venv:
  singlestore_data:

networks:
  my_network:
    driver: bridge
